ACTIVE_PROFILE: dev
SERVER_PORT: 9090

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: kevinkenobi270@gmail.com
EMAIL_PASSWORD: znzcqagupmwhqwax
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
